version: "3.9"

services:
  backend:
    build: ./backend
    container_name: transcribe-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/vosk-model:/app/vosk-model
    restart: always

  frontend:
    build: ./frontend
    container_name: transcribe-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always